language: php

addons:
  apt:
    packages:
    - apache2

script:
- find -D tree /etc/apache2/
- cat /etc/apache2/apache2.conf
- cat /etc/apache2/httpd.conf
- cat /etc/apache2/sites-available/default
