language: php

addons:
  apt:
    packages:
    - apache2

script:
- touch /var/www/index.html
- echo "Testing" >> index.html
- ls -la /var/www/
- wget http://localhost/index.html
- ls -la
- cat index.html
